
plugins {
  id "application"
  id 'java'
}

sourceSets.main.resources.srcDirs += [ rootProject.file('assets').path ]
[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
mainClassName = 'com.ap.stardew.GameServer'
application.setMainClass(mainClassName)
eclipse.project.name = appName + '-server'
java.sourceCompatibility = 17
java.targetCompatibility = 17
if (JavaVersion.current().isJava9Compatible()) {
  compileJava.options.release.set(17)
}


dependencies {
  implementation project(':common')

  implementation "com.badlogicgames.gdx:gdx-backend-headless:$gdxVersion" //Gdx headless backend for server

  implementation("org.xerial:sqlite-jdbc:3.50.3.0") // JDBC for SQLite
  implementation("org.redisson:redisson:3.50.0") // Redisson for Redis

}

run {
  workingDir = rootProject.file('assets').path
  group = "Application"
  description = "Runs the Stardew Online Server"
}

jar {
  archiveBaseName = 'server-app'
  archiveVersion = '1.0'

  manifest {
    attributes 'Main-Class' : mainClassName
  }

  doLast {
    file(archiveFile).setExecutable(true, false)
  }
}


tasks.named('processResources') {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
//tasks.named('run', JavaExec).configure {
//  // Points working directory to the resources folder
//  workingDir = file("$projectDir/src/main/resources")
//}
